export const ERROR_CODES = {
  //Auth / Session
  SESSION_EXPIRED: 'SESSION_EXPIRED',
  UNAUTHORIZED: 'UNAUTHORIZED',
  FORBIDDEN: 'FORBIDDEN',
  TOKEN_INVALID: 'TOKEN_INVALID',
  ACCOUNT_DISABLED: 'ACCOUNT_DISABLED',
  EMAIL_NOT_VERIFIED: 'EMAIL_NOT_VERIFIED',
  OTP_EXPIRED: 'OTP_EXPIRED',
  OTP_INVALID: 'OTP_INVALID',
  RESEND_TOKEN_EXPIRED: 'RESEND_TOKEN_EXPIRED',
  RESET_MAIL_SENT: 'RESET_MAIL_SENT',

  //Ressources / Données
  RESOURCE_NOT_FOUND: 'RESOURCE_NOT_FOUND',
  RESOURCE_EXISTS: 'RESOURCE_EXISTS',
  INVALID_ID: 'INVALID_ID',
  VALIDATION_ERROR: 'VALIDATION_ERROR',

  //Opérations métier
  OUT_OF_STOCK: 'OUT_OF_STOCK',
  MAX_QUANTITY_REACHED: 'MAX_QUANTITY_REACHED',
  CANNOT_DELETE_ITEM: 'CANNOT_DELETE_ITEM',
  INVALID_OPERATION: 'INVALID_OPERATION',
  CONFLICT_ERROR: 'CONFLICT_ERROR',

  //Système / Base / Réseau
  INTERNAL_ERROR: 'INTERNAL_ERROR',
  DATABASE_ERROR: 'DATABASE_ERROR',
  TIMEOUT_ERROR: 'TIMEOUT_ERROR',
  CACHE_MISS: 'CACHE_MISS',
} as const

export const SUCCESS_CODES = {
  //Auth / Session
  LOGIN_SUCCESS: 'LOGIN_SUCCESS',
  LOGIN_OTP_SENT: 'LOGIN_OTP_SENT',
  LOGOUT_SUCCESS: 'LOGOUT_SUCCESS',
  SESSION_REFRESHED: 'SESSION_REFRESHED',
  OTP_CODE_RESENT: 'OTP_CODE_RESENT',

  //Utilisateur
  ACCOUNT_CREATED: 'ACCOUNT_CREATED',
  EMAIL_VERIFIED: 'EMAIL_VERIFIED',
  PASSWORD_CHANGED: 'PASSWORD_CHANGED',
  PROFILE_UPDATED: 'PROFILE_UPDATED',

  //Ressources / Données
  ITEM_CREATED: 'ITEM_CREATED',
  ITEM_UPDATED: 'ITEM_UPDATED',
  ITEM_DELETED: 'ITEM_DELETED',
  STOCK_UPDATED: 'STOCK_UPDATED',

  //Opérations
  OPERATION_SUCCESSFUL: 'OPERATION_SUCCESSFUL',
  DATA_SAVED: 'DATA_SAVED',
  ACTION_COMPLETED: 'ACTION_COMPLETED',
} as const

export type SuccessCode = keyof typeof SUCCESS_CODES

export type ErrorCode = keyof typeof ERROR_CODES
